baseURL = "https://zesty-baklava-d1dd11.netlify.app/"
languageCode = "en-us"
title = "Anugerah's Digital Garden"
theme = "archie"
copyright = "© Anugerah"

summaryLength= 20
customcss = "css/main.css"

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto

[[params.social]]
  name= "Instagram"
  icon= "instagram"
  url= "https://www.instagram.com/brflook/"
  
[[params.social]]
  name= "Email"
  icon= "mail"
  url= "mailto:nugehoodg@gmail.com"

# Main menu Items
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "All posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 4

  [[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 5